### ISSUE TITLE
temp

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#105]

**Comment by Alchemy89** [comment]
Hey I'm uploading my Omen fighter jet for the game. It's from Autodesk maya, but I've exported it into an FBX file hopefully you guys can use it. If not, I'll go sprite with it....
[Omen8142016.fbx.zip](https://github.com/DemoProductions/fighter/files/428699/Omen8142016.fbx.zip)

**Comment by flip40** [comment]
The shmup repository has our new game in it, fighter is the old school project. I can move this over though, just mentioning if you wanted to check it out for the issues to discuss and whatnot.
