### ISSUE TITLE
Attacks damage players

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#13]
Remove our test "Q to damage player" and tie the damage call into the attack calls (at the moment that looks like it would belong in Sanji.kick()).

For now lets say Sanji.kick should do 10 points of damage?

**Comment by ghost** [comment]
10 points of damage sounds good for now. We should get this issue finished soon. I can take on this task (will start later at about 1am though)

**Comment by flip40** [comment]
Sounds good. I'll hop on the vector one.

**Comment by ghost** [comment]
Going to work on this and look at your changes in the morning actually, around 9am. Need to get some sleep
