### ISSUE TITLE
Rename "kick" to "neutral heavy"

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#17]
Just rename everything that we have named kick into heavy attack. Just making it generic as it is Sanji's heavy attack. More important for the code pieces (Character.kick() and by extension Sanji.kick() for example), but renaming the other files related would make it less confusing since they would match up.

I am guessing that there will be enough different files that are changed that we might want to do this when there are no open branches to avoid a huge merge conflict, so we will have to find a time (not critical at the moment as well, just makes things nicer when we have multiple characters).

Things that will need to be changed (afaik):
- Animation files
- Animator boolean
- References to the boolean in PlayerMovment
- Character.kick()
- Sanji.kick()
- References to those functions in PlayerMovement
- Hitbox names in HitBoxManager.cs
- Sanji prefab might need to be updated to work with the new file names

**Comment by flip40** [comment]
Might be worth a discussion on figur

**Comment by flip40** [comment]
Created discussion to help nail this down better in issue #19, we should not do this until that discussion has results as it may effect the naming convention that would be applied to this change.

**Comment by ghost** [comment]
Is our current moveset fine enough to start on this issue?

Last post here: https://github.com/DemoProductions/fighter/issues/19

**Comment by flip40** [comment]
I think so, just don't rename the kick folder for animations, when we swap to the new animations in the correctly named folder that problem will solve itself.

**Comment by ghost** [comment]
We should probably wait on this a little bit longer. More design on other things first in case we end up having to go back and changing a bunch of things

**Comment by flip40** [comment]
See #40, since some of the things you are renaming might be related you might want to go ahead and bundle that issue when you are solving this one.

**Comment by flip40** [comment]
Sure. I think we have the naming conventions fine but I agree that at the moment we have no need to change it immediately. Should be done before implementing a second character, though.

Let me write up a list of names though, so we don't have variations (i.e. neutral heavy vs heavy neutral), I'll add that to #19.
