### ISSUE TITLE
Merge fix and gravity fix

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#18]
Tested the new develop, found one small merge mistake, the old jump code made it in but without and ending brace (which made it easy enough to find).

I also found out I messed up GRAVITY by making the variable negative causing the characters to float away (yvelocity -= -.05f is equivalent to yelocity += .05f).

Just wanted to note I quickly made this fix, commit is visible at 2a70258

**Comment by ghost** [comment]
Ah ok, I was trying to figure out why the players were just going up on spawn 

I should test in Unity before I merge next time sorry about that

**Comment by flip40** [comment]
No worries, arguably I should test in Unity before making the Pull Request at all :P But I am a terrible person and didn't test that one last change I made before making the PR D:
