### ISSUE TITLE
Healthbar Prefab broken

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#23]
Healthbar prefab is broken for me on develop. Is this the same for you? For me it seems to be the same problem we had with Sanji's prefab earlier. Assuming you have the same issue, if you have a copy could you try re-committing that one, or recreate it?

**Comment by ghost** [comment]
Had the same issue and fixed it on the branch I'm currently working on. I think this has something to do with not adding in the associated .meta file. 

As a temporary fix for you the healthbar prefab just contained the healthbar script

**Comment by flip40** [comment]
Cool, I'll set that up then for my use. Will try to keep that thought on the .meta file in mind, see if I can make sure any new prefabs I might make have those in the commit.
