### ISSUE TITLE
Healthbar look/feel

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#25]

**Comment by flip40** [comment]
For the current healthbar (hp) having a dark outline (dark blue or black) with a red filling would fit. It can be simple, or it can be less simple (Brawlhalla has a very simple healthbar, for example, with just a player icon and a bar that changes color the more you get damaged).

If we are also going to implement smash style damage, we would probably want a healthbar that is always full and changes color with increased damage (filling the healthbar or removing it wouldn't make sense in that case).

I don't see any reason we can't work with a simple healthbar style. As my example with Brawlhalla, it is clear we don't really need it to be fancy. This isn't to say we can't make it fancy (keep discussing!) but at the same time I want to point out that a simple healthbar look and feel can work well too.

**Comment by ghost** [comment]
Will try implementing a healthbar that changes color the more a player gets damaged. And think about how the player can get thrown farther depending on health and the attack the player was hit with

**Comment by flip40** [comment]
You color issue #30 gave me another idea, we could start with a blue healthbar (or some other "good" color) and have it change to yellow then red as it gets lower (100-75 blue, 75-25 yellow, 25-0 red or something like that).
