### ISSUE TITLE
Sanji neutral light attack animation and hitbox

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#29]
As an exercise for myself for better understanding of how the hitboxes currently work

**Comment by flip40** [comment]
Just wanted to point you towards #31, I added a script there that will help a lot if you are trying to set up the hitboxes as part of the learning for this. Without the script I found I had trouble with internal polygons not being able to be removed, which is really annoying as they are created by the default polygon layout that gets generated when you add a polygon2d collider to a gameobject.

**Comment by ghost** [comment]
Going to try and finish this quickly and then go back to figuring out healthbars
