### ISSUE TITLE
Neutral heavy empty prefabs

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#36]
Are these supposed to be empty?

![neutralheavyemptyprefabs](https://cloud.githubusercontent.com/assets/10818718/10895221/e7548c58-8167-11e5-842a-8168fb8d2078.png)

**Comment by ghost** [comment]
https://github.com/DemoProductions/fighter/issues/17

**Comment by flip40** [comment]
Ah, is this what you were talking to me about a minute ago? I misunderstood, I'll try to fix those :/ I uploaded them along with the .meta files, annoying that they broke anyways.

**Comment by flip40** [comment]
Commit 638f652 should have fixed it. Note to self: in regards to Assets, File -> Save Project BEFORE git add and commit
