### ISSUE TITLE
Raycast hitting player it is cast from

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#41]
Causes effect: Player slides down slowly when jumping on the side of a player

**Comment by flip40** [comment]
rigidbody drag settings might be the cause of this, not sure though, but something to try.

**Comment by ghost** [comment]
Ah I didn't notice that field in Rigidbody, will try

**Comment by ghost** [comment]
The drag is already 0 though

**Comment by flip40** [comment]
Hm. Well we will have to look and see if we can find what causes it then.

**Comment by flip40** [comment]
Found it, OnCollisionEnter2D sets yvelocity to 0 (or jumps to 0) for any collision, not just collision with the floor.

The slow slide down is caused by Unity gravity on the rigidbody (which clearly is kind of meh, which is also why I use yvelocity to "override" it).

**Comment by flip40** [comment]
More specifically, it appears the raycast is actually colliding with the object you are casting from. Not sure what unity standard is for avoiding this, other than very careful raycast placement and testing.

**Comment by flip40** [comment]
Renamed to fit the actual bug, as opposed to the bug effect since we found the cause (makes the "todo" of the issue more clear as a title when looking through our bug issues).
