### ISSUE TITLE
Add jump sprites and animation

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#49]

**Comment by flip40** [comment]
https://www.facebook.com/download/1687228918165325/SpriteSheet.Final.11.11.png

**Comment by ghost** [comment]
As I do this I can also add in the rest of the sprites for idle, run, etc

**Comment by ghost** [comment]
Trying to think of a good way to trigger the new 'jumping' flag in the animator to know when to start the jump animation

**Comment by flip40** [comment]
same as kick would probably work just fine (when jump input > 0, which triggers the actual jump should also set the animation trigger), at least for starting it. This would then flow to "falling" instead of "idle" though, which would hold until jumps == 0, which should trigger landing, which flows into idle.

**Comment by flip40** [comment]
Just wanted to ask if you plan to finish this up today, I want to finish up everything marked High Priority today if possible, but don't want to take your assigned task from you if you are working on it currently or plan to get it done today. We should have a master PR by tonight or early tomorrow, IMO.

**Comment by ghost** [comment]
Sorry, saw this late. I'm planning on finishing this up early tomorrow.

**Comment by ghost** [comment]
Maybe we can merge the branch for this for now so that you can get the rest of the new sprites.

**Comment by ghost** [comment]
You can finish this for me if you want to tonight
