### ISSUE TITLE
Sprite offset

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#60]
Do you know why the new sprites have a different offset than the old sprites?

![spriteoffset](https://cloud.githubusercontent.com/assets/10818718/11162200/7b9e043e-8a4b-11e5-811e-0659ec4cb82a.png)

**Comment by flip40** [comment]
In the sprite editor did you cut the sprites with the pivot on bottom? I am assuming you might have done it in the middle, which at a guess might explain why the bottom of the hitbox is now in the middle of the player. Recutting the sprites with bottom pivot might fix it.

**Comment by ghost** [comment]
Ah that makes sense
