### ISSUE TITLE
Jump/fall/land sprites need proper hurtboxes

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#68]
Didn't add proper hurtboxes to the jump, fall, and land animations. They just continue with the last hurtbox that was used, which for the most part happens to be close enough so it isn't really noticeable, so I left it to save time. At time of writing I am going to try to add the start / game over sprites, figured that would be more interesting than hurtboxes which will be only slightly off.

**Comment by stannardtyler** [comment]
Agreed good thinkin. If it's simple out a placeholder for the end screen, even use the atart screen and I'll get one going asap tomorrow if at all possible hell of a job you guys are doing!

**Comment by ghost** [comment]
Going to try and send a PR for this later tonight

**Comment by ghost** [comment]
Update: going to try and actually send a PR for this later tonight (trying to finish up some other things)

**Comment by ghost** [comment]
I need to stop making these promises lol. A bit behind on other classes

**Comment by ghost** [comment]
Not sure why I'm getting an Index out of range each time the code is setting a collider for a frame. The animation events look right. One thing that looks off right now is for some reason the prefabs I dragged to Sanji are bolded while the ones that you did aren't. 

![question](https://cloud.githubusercontent.com/assets/10818718/11289572/0b3e6c28-8ee3-11e5-87f4-ac6343b771bd.png)

**Comment by flip40** [comment]
Error was caused because the players were using the Sanji prefab, NOT the Sanji in the Unity UI. This means they had no elements in their jump/fall/land hurtbox arrays. When modifying the Sanji in the UI you have to save the changes to the prefab by dragging from the UI onto the prefab, like when you make the new prefabs, but instead you drag him to his own prefab.

Closed by #73

**Comment by ghost** [comment]
Oh right. That was dumb
