### ISSUE TITLE
Implement character selection screen

### ISSUE THREAD

**Issue by flip40** [DemoProductions/fighter#90]

**Comment by ghost** [comment]
Do we have mockups for how this will look?

**Comment by flip40** [comment]
I think for now we just want to keep it as simple as possible just to implement it with minimal effort then we can improve it later. How about castle crashers style character select? Something similar, just 4 player windows (or just two at least) and it just scrolls through different pictures for each player.
![castle crashers_2015-01-09_000041420832972-full](https://cloud.githubusercontent.com/assets/10754057/11571801/0551e5b2-99b3-11e5-95b1-5da5674f04ea.jpg)

Code framework is something around using static variables to keep track of the character selection for each player (and number of players who joined, if we do up to four), which would be used by the playerspawner script to create a new player for each player who joined, and set the player's selected character. IIRC static variables are remembered between scenes, not sure on the specifics though.
